# Generated by Django 6.0.2 on 2026-02-20 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basin_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasinRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('upstream_to_downstream', 'upstream_to_downstream'), ('other', 'other')], max_length=64)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('from_basin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_relations', to='monitoring.basin')),
                ('to_basin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_relations', to='monitoring.basin')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_basin', 'to_basin', 'relation_type'), name='unique_basin_relation')],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('source', models.CharField(default='unknown', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='monitoring.basin')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='monitoring.datatype')),
            ],
            options={
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['basin', 'data_type', 'datetime'], name='idx_basin_dt_type'), models.Index(fields=['data_type', 'datetime'], name='idx_type_datetime'), models.Index(fields=['datetime'], name='idx_datetime')],
                'constraints': [models.UniqueConstraint(fields=('basin', 'data_type', 'datetime', 'source'), name='unique_observation_per_source_dt')],
            },
        ),
    ]
